version: "3"

services:
  postgresql:
    build: ./build/postgresql
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    ports:
      - "15432:5432"
    networks:
      - testMIT

  keycloak:
    depends_on:
      - postgresql
    build: ./build/keycloak
    restart: unless-stopped
    environment:
      DB_ADDR: postgresql
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - testMIT

networks:
  testMIT:
    driver: bridge