version: "3"

services:
  nginx:
    build: ./build/nginx/
    ports:
      - "80:80"
    depends_on:
      - keycloak
      - core
    volumes:
      - ./build/nginx/:/etc/nginx/conf.d/
    networks:
      - testMIT


  postgresql:
    build: ./build/postgresql
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    volumes:
      - ~/tmp/postgresql_mgt:/var/lib/postgresql
    ports:
      - "15432:5432"
    networks:
      - testMIT

  keycloak:
    depends_on:
      - postgresql
    build: ./build/keycloak
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./build/keycloak/import:/tmp/import
    environment:
      DB_ADDR: postgresql
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      PROXY_ADDRESS_FORWARDING: true
      REDIRECT_SOCKET: "proxy-http"
      KEYCLOAK_FRONTEND_URL: http://localhost/auth
      KEYCLOAK_IMPORT: /tmp/import/general.json
    networks:
      - testMIT

  core:
    depends_on:
      - keycloak
    build: ./components/app1
    environment:
      SECRET_KEY: ${KC_SECRET_KEY_CORE}
    ports:
      - "8080:8080"
    networks:
      - testMIT

networks:
  testMIT:
    driver: bridge